// mathspace/fxmath.hpp — transcendental functions over fx64 with fixed work.
//
// sin, cos, atan2, exp, log, pow. Each one runs the same integer instruction
// sequence for every input: the loops have literal bounds, there is no
// convergence test, no early exit, and no recursion (fxmath_test.cpp scans
// this file for `while`, `do`, `goto` and non-literal `for` bounds). Debug,
// Release, UBSan and Wasm therefore agree bit for bit, and a rule that calls
// sin ten thousand times a tick costs the same ten thousand times.
//
// Method. sin/cos/atan2 are CORDIC (rotation and vectoring mode) in a Q3.60
// working format for CORDIC_ITER = 48 iterations, which puts the angle
// residual near 2^-48 and the result, rounded to the grid, within one
// Q32.32 ulp of the true value. exp and log are the shift-and-add ("BKM") scheme over the factors
// 1 + 2^-i, i = 1..BKM_ITER = 58, in Q5.58: exp multiplies the factors
// whose logs fit under the residual, log divides them out of the mantissa.
// pow is exp(y * log(x)) with the product on the Q32.32 grid, so its
// relative error grows linearly with |y| (about |y| * 2^-32).
//
// Every constant is floor(value * 2^k), generated by tools/gen_fxmath/gen.py
// (mpmath at 60 digits); nothing here is computed from a floating-point
// value at compile time or run time.
//
// Contract violations follow fx64.hpp: log of a non-positive value and pow
// of a non-positive base return 0 in every build and assert in Debug. exp
// saturates at the largest fx64 when the result would not fit, and
// returns 0 when it would floor to 0; both are ordinary results, not
// violations.
#pragma once

#include "mathspace/fx64.hpp"

#include <cstdint>

namespace ddsim {
namespace fxmath {

inline constexpr unsigned CORDIC_ITER = 48;
inline constexpr unsigned BKM_ITER = 58;

// Generated by tools/gen_fxmath/gen.py tables; do not edit by hand.
inline constexpr std::int64_t PI_32 = 13493037704;
inline constexpr std::int64_t TWO_PI_32 = 26986075409;
inline constexpr std::int64_t HALF_PI_32 = 6746518852;
inline constexpr std::int64_t LN2_32 = 2977044471;
inline constexpr std::int64_t PI_60 = 3622009729038561421;
inline constexpr std::int64_t HALF_PI_60 = 1811004864519280710;
inline constexpr std::int64_t TWO_PI_60 = 7244019458077122842;
inline constexpr std::int64_t TWO_PI_MID = 11821338;
inline constexpr std::int64_t TWO_PI_LO = 103166740;
inline constexpr std::int64_t LN2_58 = 199786072581291494;
inline constexpr std::int64_t CORDIC_K_60 = 700114967507363238;
inline constexpr std::int64_t ATAN_60[CORDIC_ITER] = {
    905502432259640355,
    534549298976576474,
    282441168888798124,
    143371547418228444,
    71963988336308046,
    36017075762092178,
    18012932708689205,
    9007016009513623,
    4503576721087963,
    2251796950380270,
    1125899548928887,
    562949908682075,
    281474971118250,
    140737487656277,
    70368744090282,
    35184372077909,
    17592186043050,
    8796093022037,
    4398046511082,
    2199023255549,
    1099511627775,
    549755813887,
    274877906943,
    137438953471,
    68719476735,
    34359738367,
    17179869183,
    8589934591,
    4294967295,
    2147483647,
    1073741823,
    536870911,
    268435455,
    134217727,
    67108863,
    33554431,
    16777215,
    8388607,
    4194303,
    2097151,
    1048575,
    524287,
    262143,
    131071,
    65535,
    32767,
    16383,
    8191,
};
inline constexpr std::int64_t LN1P_58[BKM_ITER + 1] = {
    0,  // index 0 is unused: the factors are 1 + 2^-i for i >= 1
    116867360626410687,
    64316749731123469,
    33948648671529879,
    17473857550206284,
    8869326752330496,
    4468777517187569,
    2243049266878946,
    1123706593485176,
    562400912388366,
    281337627170184,
    140703139797676,
    70360155640917,
    35182224779930,
    17591649195348,
    8795958807210,
    4398012957013,
    2199014866986,
    1099509530629,
    549755289600,
    274877775872,
    137438920704,
    68719468544,
    34359736320,
    17179868672,
    8589934464,
    4294967264,
    2147483640,
    1073741822,
    536870911,
    268435455,
    134217727,
    67108863,
    33554431,
    16777215,
    8388607,
    4194303,
    2097151,
    1048575,
    524287,
    262143,
    131071,
    65535,
    32767,
    16383,
    8191,
    4095,
    2047,
    1023,
    511,
    255,
    127,
    63,
    31,
    15,
    7,
    3,
    1,
    0,
};

// Position of the highest set bit of a non-zero word, by six fixed halving
// steps rather than a loop or a builtin.
constexpr unsigned msb64(std::uint64_t m) {
    unsigned n = 0;
    if (m >> 32) { m >>= 32; n += 32; }
    if (m >> 16) { m >>= 16; n += 16; }
    if (m >> 8) { m >>= 8; n += 8; }
    if (m >> 4) { m >>= 4; n += 4; }
    if (m >> 2) { m >>= 2; n += 2; }
    if (m >> 1) { n += 1; }
    return n;
}

// |v| as an unsigned word; INT64_MIN maps to 2^63 without signed overflow.
constexpr std::uint64_t umag(std::int64_t v) {
    return v < 0 ? (std::uint64_t{0} - static_cast<std::uint64_t>(v)) : static_cast<std::uint64_t>(v);
}

// Arithmetic shift by a signed amount: left for s > 0, right (floor) for
// s < 0. Callers keep |s| < 64.
constexpr std::int64_t shift_signed(std::int64_t v, int s) {
    return s >= 0 ? static_cast<std::int64_t>(static_cast<std::uint64_t>(v) << s) : (v >> (-s));
}

// Q3.60 to Q32.32. The CORDIC working value is off by up to about 2^-47
// in either direction, so this rounds to nearest rather than flooring: a
// floor would turn sin(0) into -2^-32 and cos(0) into 1 - 2^-32. exp and
// log never over-approximate and keep the floor.
constexpr std::int64_t to_grid(std::int64_t q60) {
    return (q60 + (std::int64_t{1} << 27)) >> 28;
}

struct SinCos {
    fx64 sin;
    fx64 cos;
};

// Both at once, since CORDIC produces both. The angle is reduced modulo
// 2 pi: k = floor(angle / TWO_PI_32) on the Q32.32 grid (the multiply
// below wraps for the largest inputs; -fwrapv makes that defined and the
// residue is still correct modulo 2^64), then the residue is refined in
// Q3.60 with 2 pi carried to 88 fractional bits (TWO_PI_32, TWO_PI_MID,
// TWO_PI_LO), so a full-range input loses about 2^-59 of angle rather than
// half an ulp per period. TWO_PI_32 is below 2 pi, so k can be one too
// large and one correction brings the residue back into [0, 2 pi). The
// residue is folded into [-pi/2, pi/2] and rotated.
constexpr SinCos sincos(fx64 angle) {
    const std::int64_t k = div_q32(angle.raw, TWO_PI_32) >> 32;  // |k| < 2^29
    std::int64_t r = ((angle.raw - k * TWO_PI_32) << 28) - k * TWO_PI_MID - ((k * TWO_PI_LO) >> 28);
    if (r < 0) {
        r += TWO_PI_60;  // [0, 2 pi)
    }
    if (r > PI_60) {
        r -= TWO_PI_60;  // (-pi, pi]
    }
    bool negate_cos = false;
    if (r > HALF_PI_60) {
        r = PI_60 - r;
        negate_cos = true;
    } else if (r < -HALF_PI_60) {
        r = -PI_60 - r;
        negate_cos = true;
    }
    std::int64_t x = CORDIC_K_60;
    std::int64_t y = 0;
    std::int64_t z = r;  // |r| <= pi/2 in Q3.60
    for (unsigned i = 0; i < CORDIC_ITER; ++i) {
        const std::int64_t xs = x >> i;
        const std::int64_t ys = y >> i;
        if (z >= 0) {
            x -= ys;
            y += xs;
            z -= ATAN_60[i];
        } else {
            x += ys;
            y -= xs;
            z += ATAN_60[i];
        }
    }
    if (negate_cos) {
        x = -x;
    }
    return SinCos{fx64::from_raw(to_grid(y)), fx64::from_raw(to_grid(x))};
}

constexpr fx64 sin(fx64 angle) { return sincos(angle).sin; }
constexpr fx64 cos(fx64 angle) { return sincos(angle).cos; }

// Angle of (x, y) in (-pi, pi]. atan2(0, 0) is 0. The pair is scaled by a
// common power of two so the larger magnitude has its top bit at 59 (the
// CORDIC gain of 1.647 then keeps every intermediate below 2^62), a
// negative x is flipped through the origin and the half turn added back.
constexpr fx64 atan2(fx64 y, fx64 x) {
    if (x.raw == 0 && y.raw == 0) {
        return fx64::from_raw(0);
    }
    const std::uint64_t m = umag(x.raw) > umag(y.raw) ? umag(x.raw) : umag(y.raw);
    const int s = 59 - static_cast<int>(msb64(m));
    std::int64_t vx = shift_signed(x.raw, s);
    std::int64_t vy = shift_signed(y.raw, s);
    const bool flipped = vx < 0;
    if (flipped) {
        vx = -vx;
        vy = -vy;
    }
    std::int64_t z = 0;
    for (unsigned i = 0; i < CORDIC_ITER; ++i) {
        const std::int64_t xs = vx >> i;
        const std::int64_t ys = vy >> i;
        if (vy >= 0) {
            vx += ys;
            vy -= xs;
            z += ATAN_60[i];
        } else {
            vx -= ys;
            vy += xs;
            z -= ATAN_60[i];
        }
    }
    if (flipped) {
        z = y.raw >= 0 ? z + PI_60 : z - PI_60;
    }
    return fx64::from_raw(to_grid(z));
}

// e^t for t = n ln2 + r given as a Q5.58 exponent: r in [0, ln2) is
// decomposed greedily over ln(1 + 2^-i), the matching factors multiply
// into y, and y (in [1, 2) Q5.58) is scaled by 2^n onto the Q32.32 grid.
// Saturates at INT64_MAX when the result would not fit (n >= 31, or n == 30
// with y reaching 2), and floors to 0 when it would.
constexpr std::int64_t exp_core(std::int64_t t58) {
    std::int64_t n = t58 / LN2_58;
    std::int64_t r = t58 - n * LN2_58;
    if (r < 0) {  // C++ division truncates toward zero; floor it
        r += LN2_58;
        n -= 1;
    }
    std::int64_t y = std::int64_t{1} << 58;
    for (unsigned i = 1; i <= BKM_ITER; ++i) {
        if (r >= LN1P_58[i]) {
            r -= LN1P_58[i];
            y += y >> i;
        }
    }
    const int s = static_cast<int>(n) - 26;  // Q5.58 * 2^n to Q32.32
    if (s > 4 || (s == 4 && y >= (std::int64_t{1} << 59))) {
        return INT64_MAX;
    }
    if (s < -63) {
        return 0;
    }
    return shift_signed(y, s);
}

// ln x as Q5.58 for x > 0 (the caller has checked): x = m 2^e with m in
// [1, 2) as Q5.58; ln m by dividing out the factors 1 + 2^-i, then e ln2
// added. |result| < 23 ln2 < 16, well inside Q5.58.
constexpr std::int64_t log_core(std::int64_t raw) {
    const int e = static_cast<int>(msb64(static_cast<std::uint64_t>(raw))) - 32;
    const std::int64_t m = shift_signed(raw, 26 - e);  // top bit at 58: [1, 2) Q5.58
    std::int64_t y = std::int64_t{1} << 58;
    std::int64_t r = 0;
    for (unsigned i = 1; i <= BKM_ITER; ++i) {
        const std::int64_t t = y + (y >> i);
        if (t <= m) {
            y = t;
            r += LN1P_58[i];
        }
    }
    return r + e * LN2_58;
}

// The exponent range exp_core accepts: above it the result saturates,
// below it the result floors to 0 (e^x * 2^32 < 1/2). Both are ordinary
// results, not contract violations.
inline constexpr std::int64_t EXP_MAX_32 = 31 * LN2_32;
inline constexpr std::int64_t EXP_MIN_32 = -33 * LN2_32;

// e^x. The Q32.32 input is exact in Q5.58 once inside the accepted range.
constexpr fx64 exp(fx64 x) {
    if (x.raw >= EXP_MAX_32) {
        return fx64::from_raw(INT64_MAX);
    }
    if (x.raw < EXP_MIN_32) {
        return fx64::from_raw(0);
    }
    return fx64::from_raw(exp_core(x.raw << 26));
}

// ln x for x > 0, floored to the grid. Non-positive x returns 0 (and
// asserts in Debug).
constexpr fx64 log(fx64 x) {
    DDSIM_ASSERT(x.raw > 0);
    if (x.raw <= 0) {
        return fx64::from_raw(0);
    }
    return fx64::from_raw(log_core(x.raw) >> 26);
}

// x^y for x > 0: exp(y ln x) with the product formed in Q5.58, so the
// result carries the same relative error as exp (about 2^-50), not one
// that grows with |y|. The range check runs on a Q32.32 copy of the
// product first, so the Q5.58 product is only formed when it fits.
// x <= 0 returns 0 (and asserts in Debug); y == 0 gives 1 for any x > 0.
constexpr fx64 pow(fx64 x, fx64 y) {
    DDSIM_ASSERT(x.raw > 0);
    if (x.raw <= 0) {
        return fx64::from_raw(0);
    }
    const std::int64_t l58 = log_core(x.raw);
    const std::int64_t t32 = mul_q32(y.raw, l58 >> 26);
    if (t32 >= EXP_MAX_32) {
        return fx64::from_raw(INT64_MAX);
    }
    if (t32 < EXP_MIN_32 - fx64::ONE) {  // a whole unit of slack for the coarse product
        return fx64::from_raw(0);
    }
    return fx64::from_raw(exp_core(mul_q32(y.raw, l58)));
}

} // namespace fxmath
} // namespace ddsim
