[package]
name = "tapestry-render"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = "0.34.1"
tapestry-view = { version = "0.1.0", path = "../view" }
wgpu = "30"

[dev-dependencies]
png = "0.18.1"
pollster = "1.0.1"
tapestry-mock = { path = "../mock" }
