#!/usr/bin/env python3
"""gen.py — constants for include/ddsim/fxmath.hpp and the oracle table for
tests/mathspace/fxmath_test.cpp.

The engine may not compute a floating-point value, but its tests may check
it against one computed elsewhere. This script does that elsewhere: mpmath
at 60 decimal digits, every constant floored to the fixed-point grid, every
oracle entry floor(f(raw / 2^32) * 2^32). Inputs are drawn with splitmix64
from a fixed seed so the table is reproducible.

Usage:
  python3 tools/gen_fxmath/gen.py tables   > (paste into fxmath.hpp)
  python3 tools/gen_fxmath/gen.py oracle   > tests/mathspace/fxmath_oracle.inc
"""
import sys
from mpmath import mp, mpf, sin, cos, atan2, exp, log, atan, sqrt, pi, floor, power

mp.dps = 60
Q32 = mpf(2) ** 32
Q58 = mpf(2) ** 58
Q60 = mpf(2) ** 60
I64_MAX = (1 << 63) - 1
I64_MIN = -(1 << 63)

CORDIC_ITER = 48
BKM_ITER = 58


def fl(v):
    return int(floor(v))


def clamp(v):
    return max(I64_MIN, min(I64_MAX, v))


def lit(v):
    """C++ literal; INT64_MIN has no signed literal of its own."""
    return f"({v + 1} - 1)" if v == I64_MIN else str(v)


def tables():
    print(f"// Generated by tools/gen_fxmath/gen.py tables; do not edit by hand.")
    print(f"inline constexpr std::int64_t PI_32 = {fl(pi * Q32)};")
    print(f"inline constexpr std::int64_t TWO_PI_32 = {fl(2 * pi * Q32)};")
    print(f"inline constexpr std::int64_t HALF_PI_32 = {fl(pi / 2 * Q32)};")
    print(f"inline constexpr std::int64_t LN2_32 = {fl(log(2) * Q32)};")
    print(f"inline constexpr std::int64_t PI_60 = {fl(pi * Q60)};")
    print(f"inline constexpr std::int64_t HALF_PI_60 = {fl(pi / 2 * Q60)};")
    two_pi_60 = fl(2 * pi * Q60)
    print(f"inline constexpr std::int64_t TWO_PI_60 = {two_pi_60};")
    # 2 pi to 88 fractional bits in three parts: Q32.32, then two 28-bit slices.
    print(f"inline constexpr std::int64_t TWO_PI_MID = {two_pi_60 - fl(2 * pi * Q32) * 2**28};")
    print(f"inline constexpr std::int64_t TWO_PI_LO = {fl(2 * pi * mpf(2) ** 88) - two_pi_60 * 2**28};")
    print(f"inline constexpr std::int64_t LN2_58 = {fl(log(2) * Q58)};")
    k = mpf(1)
    for i in range(CORDIC_ITER):
        k /= sqrt(1 + mpf(2) ** (-2 * i))
    print(f"inline constexpr std::int64_t CORDIC_K_60 = {fl(k * Q60)};")
    print(f"inline constexpr std::int64_t ATAN_60[CORDIC_ITER] = {{")
    for i in range(CORDIC_ITER):
        print(f"    {fl(atan(mpf(2) ** -i) * Q60)},")
    print("};")
    print(f"inline constexpr std::int64_t LN1P_58[BKM_ITER + 1] = {{")
    print("    0,  // index 0 is unused: the factors are 1 + 2^-i for i >= 1")
    for i in range(1, BKM_ITER + 1):
        print(f"    {fl(log(1 + mpf(2) ** -i) * Q58)},")
    print("};")


class Rng:
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFFFFFFFFFF

    def next(self):
        self.s = (self.s + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        return z ^ (z >> 31)

    def i64(self, lo, hi):
        """uniform integer in [lo, hi]"""
        return lo + self.next() % (hi - lo + 1)

    def real(self, lo, hi):
        """raw fx64 uniform in [lo, hi] real units"""
        return self.i64(int(lo * 2**32), int(hi * 2**32))

    def logreal(self, lo_exp, hi_exp):
        """raw fx64 positive, log-uniform between 2^lo_exp and 2^hi_exp"""
        e = self.i64(lo_exp, hi_exp)
        m = 2**32 + self.next() % (2**32)  # Q32.32 mantissa in [1, 2)
        return max(1, (m << 32) >> (32 - e))


def fx(raw):
    return mpf(raw) / Q32


def emit1(name, samples, f):
    print(f"// {name}: {{input raw, floor(f(input) * 2^32)}}")
    print(f"inline constexpr std::int64_t {name}[][2] = {{")
    for x in samples:
        print(f"    {{{lit(x)}, {lit(clamp(fl(f(fx(x)) * Q32)))}}},")
    print("};")


def emit2(name, samples, f):
    print(f"// {name}: {{a raw, b raw, floor(f(a, b) * 2^32)}}")
    print(f"inline constexpr std::int64_t {name}[][3] = {{")
    for a, b in samples:
        print(f"    {{{lit(a)}, {lit(b)}, {lit(clamp(fl(f(fx(a), fx(b)) * Q32)))}}},")
    print("};")


def oracle():
    rng = Rng(0x0123456789ABCDEF)
    print("// Generated by tools/gen_fxmath/gen.py oracle; do not edit by hand.")
    print("// Truth values from mpmath at 60 digits; see the script for the sampling.")
    # sin/cos: the same inputs. Small, near quadrant boundaries, moderate, huge.
    trig = [0, 1, -1, 2**32, -(2**32), fl(pi / 2 * Q32), fl(pi * Q32), fl(2 * pi * Q32),
            fl(3 * pi / 2 * Q32), -fl(pi / 2 * Q32), fl(pi / 4 * Q32), fl(pi / 6 * Q32),
            I64_MAX, I64_MIN, (1 << 62) + 12345]
    for _ in range(64):
        trig.append(rng.real(-8, 8))
    for _ in range(48):
        trig.append(rng.real(-1000, 1000))
    for _ in range(24):
        trig.append(rng.real(-2**31, 2**31 - 1))
    for k in range(-8, 9):
        trig.append(fl(k * pi / 2 * Q32) + rng.i64(-3, 3))
    emit1("SIN_ORACLE", trig, sin)
    emit1("COS_ORACLE", trig, cos)
    # atan2: axes, random, extreme ratios, extreme magnitudes.
    at = [(0, 2**32), (2**32, 0), (0, -(2**32)), (-(2**32), 0), (2**32, 2**32), (-(2**32), -(2**32)),
          (1, 1), (1, -1), (-1, -1), (I64_MAX, 1), (1, I64_MAX), (I64_MIN, I64_MIN), (I64_MAX, I64_MIN),
          (1, I64_MIN), (-1, I64_MIN), (2**32, 2**62)]
    for _ in range(64):
        at.append((rng.real(-100, 100), rng.real(-100, 100)))
    for _ in range(32):
        at.append((rng.i64(-(2**40), 2**40), rng.i64(1, 2**20)))
    for _ in range(32):
        at.append((rng.i64(I64_MIN, I64_MAX), rng.i64(I64_MIN, I64_MAX)))
    emit2("ATAN2_ORACLE", at, atan2)
    # exp: domain [-23, 21.48]; outside is clamped by the implementation and tested by hand.
    ex = [0, 1, -1, 2**32, -(2**32), fl(log(2) * Q32), -fl(log(2) * Q32), 10 * 2**32, -10 * 2**32,
          20 * 2**32, fl(mpf(21) * Q32), -22 * 2**32, fl(mpf("-22.9") * Q32), 2**16, -(2**16)]
    for _ in range(96):
        ex.append(rng.real(-23, 21.4))
    for _ in range(32):
        ex.append(rng.real(-2, 2))
    emit1("EXP_ORACLE", ex, exp)
    # log: positive, log-uniform over the whole range.
    lg = [1, 2, 3, 2**32, 2**33, 2**31, 3 * 2**31, I64_MAX, 10 * 2**32, fl(exp(1) * Q32)]
    for _ in range(128):
        lg.append(rng.logreal(-32, 30))
    emit1("LOG_ORACLE", lg, log)
    # pow: base positive log-uniform in [2^-8, 2^8], exponent in [-8, 8] with the
    # result kept in range; a few integer exponents.
    pw = [(2**32, 0), (2**33, 2**32), (2**33, 10 * 2**32), (2**33, -(2**32)), (4 * 2**32, 2**31),
          (9 * 2**32, 2**31), (2**32, 100 * 2**32), (2**31, 2 * 2**32), (100 * 2**32, 3 * 2**32)]
    while len(pw) < 96:
        a = rng.logreal(-8, 8)
        b = rng.real(-8, 8)
        v = power(fx(a), fx(b))
        if v * Q32 < 2**62 and v * Q32 > 2**-4:
            pw.append((a, b))
    emit2("POW_ORACLE", pw, power)


if __name__ == "__main__":
    {"tables": tables, "oracle": oracle}[sys.argv[1]]()
