[package]
name = "tapestry-canvas-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "tapestry-canvas"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "default_fonts", "wayland", "x11"] }
glam = "0.34.1"
tapestry-canvas = { version = "0.1.0", path = "../../crates/canvas" }
png = "0.18.1"
egui_dock = "0.21.1"
egui_extras = { version = "0.36.2", default-features = false }
