// fxmath against an mpmath oracle and a fixed-work scan of the header.
//
// tests/mathspace/fxmath_oracle.inc is generated by tools/gen_fxmath/gen.py:
// inputs on the Q32.32 grid and floor(f(input) * 2^32) computed at 60 digits.
// The engine cannot reproduce those values, only approach them, so each
// function has a stated tolerance in ulps (2^-32) that the test also reports
// as a measured maximum. The tolerances are the contract; tightening them
// is a change to fxmath.hpp, loosening them is a regression.
#include "mathspace/fxmath.hpp"

#include <doctest.h>

#include <cstdint>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>

#include "fxmath_oracle.inc"

namespace {

using ddsim::fx64;
namespace fm = ddsim::fxmath;

std::int64_t absdiff(std::int64_t a, std::int64_t b) {
    return a > b ? a - b : b - a;
}

template <typename F>
void checkUnary(const char* name, const std::int64_t (*table)[2], std::size_t n, F f, std::int64_t tol) {
    std::int64_t worst = 0;
    for (std::size_t i = 0; i < n; ++i) {
        const std::int64_t got = f(fx64::from_raw(table[i][0])).raw;
        const std::int64_t d = absdiff(got, table[i][1]);
        if (d > worst) {
            worst = d;
        }
        if (d > tol) {
            CHECK_MESSAGE(false, std::string(name) << "(" << table[i][0] << ") got " << got << " want " << table[i][1] << " off by " << d);
        }
    }
    MESSAGE(std::string(name) << ": " << n << " oracle entries, worst " << worst << " ulp, tolerance " << tol);
}

// A relative tolerance: |got - want| <= tol + (|want| >> shift).
template <typename F>
void checkBinary(const char* name, const std::int64_t (*table)[3], std::size_t n, F f, std::int64_t tol, unsigned shift) {
    std::int64_t worst = 0;
    for (std::size_t i = 0; i < n; ++i) {
        const std::int64_t got = f(fx64::from_raw(table[i][0]), fx64::from_raw(table[i][1])).raw;
        const std::int64_t want = table[i][2];
        const std::int64_t d = absdiff(got, want);
        const std::int64_t allowed = tol + ((want < 0 ? -want : want) >> shift);
        if (d > worst) {
            worst = d;
        }
        if (d > allowed) {
            CHECK_MESSAGE(false, std::string(name) << "(" << table[i][0] << ", " << table[i][1] << ") got " << got << " want " << want << " off by " << d << " allowed " << allowed);
        }
    }
    MESSAGE(std::string(name) << ": " << n << " oracle entries, worst " << worst << " ulp");
}

template <std::size_t N>
constexpr std::size_t count(const std::int64_t (&)[N][2]) { return N; }
template <std::size_t N>
constexpr std::size_t count(const std::int64_t (&)[N][3]) { return N; }

std::string readHeader() {
    std::ifstream in(std::string(MATHSPACE_GOLDEN_DIR) + "/../../../include/mathspace/fxmath.hpp");
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

} // namespace

TEST_CASE("fxmath: sin and cos within 1 ulp of the oracle") {
    checkUnary("sin", SIN_ORACLE, count(SIN_ORACLE), [](fx64 x) { return fm::sin(x); }, 1);
    checkUnary("cos", COS_ORACLE, count(COS_ORACLE), [](fx64 x) { return fm::cos(x); }, 1);
}

TEST_CASE("fxmath: atan2 within 1 ulp of the oracle") {
    checkBinary("atan2", ATAN2_ORACLE, count(ATAN2_ORACLE), [](fx64 y, fx64 x) { return fm::atan2(y, x); }, 1, 63);
}

TEST_CASE("fxmath: exp within 2^-50 relative of the oracle") {
    // The 58 floored factor products each lose up to 2^-58 relative, so
    // 2 ulps plus 2^-50 of the magnitude covers the result.
    std::int64_t worst = 0;
    for (std::size_t i = 0; i < count(EXP_ORACLE); ++i) {
        const std::int64_t got = fm::exp(fx64::from_raw(EXP_ORACLE[i][0])).raw;
        const std::int64_t want = EXP_ORACLE[i][1];
        const std::int64_t d = absdiff(got, want);
        const std::int64_t allowed = 2 + (want >> 50);
        if (d > worst) {
            worst = d;
        }
        if (d > allowed) {
            CHECK_MESSAGE(false, "exp(" << EXP_ORACLE[i][0] << ") got " << got << " want " << want << " off by " << d);
        }
    }
    MESSAGE("exp: " << count(EXP_ORACLE) << " oracle entries, worst " << worst << " ulp");
}

TEST_CASE("fxmath: log within 2 ulp of the oracle") {
    checkUnary("log", LOG_ORACLE, count(LOG_ORACLE), [](fx64 x) { return fm::log(x); }, 2);
}

TEST_CASE("fxmath: pow within 2^-48 relative of the oracle") {
    checkBinary("pow", POW_ORACLE, count(POW_ORACLE), [](fx64 x, fx64 y) { return fm::pow(x, y); }, 2, 48);
}

TEST_CASE("fxmath: edges and contract violations are fixed values") {
    CHECK(fm::sin(fx64::from_raw(0)).raw == 0);
    CHECK(fm::cos(fx64::from_raw(0)).raw == fx64::ONE);
    CHECK(fm::atan2(fx64::from_raw(0), fx64::from_raw(0)).raw == 0);
    CHECK(fm::atan2(fx64::from_raw(0), fx64::from_int(-1)).raw == fm::to_grid(fm::PI_60));
    CHECK(fm::atan2(fx64::from_int(1), fx64::from_raw(0)).raw == fm::to_grid(fm::HALF_PI_60));
    CHECK(fm::exp(fx64::from_raw(0)).raw == fx64::ONE);
    CHECK(fm::exp(fx64::from_int(22)).raw == INT64_MAX);
    CHECK(fm::exp(fx64::from_int(2000)).raw == INT64_MAX);
    CHECK(fm::exp(fx64::from_int(-23)).raw == 0);
    CHECK(fm::exp(fx64::from_raw(INT64_MIN)).raw == 0);
    CHECK(fm::log(fx64::from_int(1)).raw == 0);
    CHECK(fm::log(fx64::from_int(2)).raw == fm::LN2_32);
    CHECK(fm::pow(fx64::from_int(7), fx64::from_raw(0)).raw == fx64::ONE);
    CHECK(fm::pow(fx64::from_int(2), fx64::from_int(10)).raw == fx64::from_int(1024).raw);
    CHECK(fm::pow(fx64::from_int(4), fx64::from_raw(fx64::ONE / 2)).raw == fx64::from_int(2).raw);
    CHECK(fm::pow(fx64::from_int(2), fx64::from_int(40)).raw == INT64_MAX);
    CHECK(fm::pow(fx64::from_int(2), fx64::from_int(-40)).raw == 0);
#ifdef NDEBUG
    CHECK(fm::log(fx64::from_raw(0)).raw == 0);
    CHECK(fm::log(fx64::from_int(-3)).raw == 0);
    CHECK(fm::pow(fx64::from_int(-3), fx64::from_int(2)).raw == 0);
#endif
}

// FNV-1a over the raw result of every oracle input, in table order. The
// oracle tolerances bound the error; this pins the exact bits, so Debug,
// Release, UBSan and Wasm must produce this one value. Re-pin only with a
// change to fxmath.hpp that is meant to change results.
constexpr std::uint64_t kFxmathDigest = 727731501767094518ULL;

TEST_CASE("fxmath: the bit-exact digest of every oracle input") {
    std::uint64_t h = 0xcbf29ce484222325ULL;
    const auto mix = [&h](std::int64_t v) {
        std::uint64_t u = static_cast<std::uint64_t>(v);
        for (unsigned i = 0; i < 8; ++i) {
            h ^= u & 0xffu;
            h *= 0x100000001b3ULL;
            u >>= 8;
        }
    };
    for (const auto& e : SIN_ORACLE) {
        mix(fm::sin(fx64::from_raw(e[0])).raw);
        mix(fm::cos(fx64::from_raw(e[0])).raw);
    }
    for (const auto& e : ATAN2_ORACLE) {
        mix(fm::atan2(fx64::from_raw(e[0]), fx64::from_raw(e[1])).raw);
    }
    for (const auto& e : EXP_ORACLE) {
        mix(fm::exp(fx64::from_raw(e[0])).raw);
    }
    for (const auto& e : LOG_ORACLE) {
        mix(fm::log(fx64::from_raw(e[0])).raw);
    }
    for (const auto& e : POW_ORACLE) {
        mix(fm::pow(fx64::from_raw(e[0]), fx64::from_raw(e[1])).raw);
    }
    MESSAGE("fxmath digest " << h);
    CHECK(h == kFxmathDigest);
}

TEST_CASE("fxmath: every function is a constant expression") {
    // Compile-time evaluation proves each call terminates by construction
    // and touches nothing but its arguments and the tables.
    static_assert(fm::sin(fx64::from_raw(0)).raw == 0);
    static_assert(fm::cos(fx64::from_raw(0)).raw == fx64::ONE);
    static_assert(fm::atan2(fx64::from_int(1), fx64::from_int(1)).raw > 0);
    static_assert(fm::exp(fx64::from_raw(0)).raw == fx64::ONE);
    static_assert(fm::log(fx64::from_int(1)).raw == 0);
    static_assert(fm::pow(fx64::from_int(3), fx64::from_int(0)).raw == fx64::ONE);
    CHECK(true);
}

TEST_CASE("fxmath: the header does fixed work (op-count scan)") {
    std::string header = readHeader();
    REQUIRE(!header.empty());
    header = std::regex_replace(header, std::regex(R"(//[^\n]*)"), "");  // comments may say "do not"
    REQUIRE(header.find("CORDIC_ITER") != std::string::npos);
    // No open-ended control flow.
    const std::regex banned(R"((^|[^A-Za-z0-9_])(while|do|goto|__builtin_clz)([^A-Za-z0-9_]|$))");
    CHECK(!std::regex_search(header, banned));
    // Every for loop runs a named literal iteration count, up or down.
    const std::regex any_for(R"(for \()");
    const std::regex fixed_for(R"(for \(unsigned i = (0|1); i (<|<=) (CORDIC_ITER|BKM_ITER); \+\+i\))");
    const auto total = std::distance(std::sregex_iterator(header.begin(), header.end(), any_for), std::sregex_iterator());
    const auto fixed = std::distance(std::sregex_iterator(header.begin(), header.end(), fixed_for), std::sregex_iterator());
    CHECK(total == fixed);
    CHECK(total == 4);  // sincos, atan2, exp, log
    // The iteration counts are literals in the header, not derived.
    CHECK(header.find("inline constexpr unsigned CORDIC_ITER = 48;") != std::string::npos);
    CHECK(header.find("inline constexpr unsigned BKM_ITER = 58;") != std::string::npos);
}
